<?php

namespace Database\Seeders;

use App\Models\TelefoneDdi;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TelefoneDdisSeeder extends Seeder
{
    public function run()
    {
        TelefoneDdi::create(['pais' => 'Afghanistão', 'ddi' => '93']);
        TelefoneDdi::create(['pais' => 'África do Sul', 'ddi' => '27']);
        TelefoneDdi::create(['pais' => 'Albânia', 'ddi' => '355']);
        TelefoneDdi::create(['pais' => 'Alemanha', 'ddi' => '49']);
        TelefoneDdi::create(['pais' => 'Andora', 'ddi' => '376']);
        TelefoneDdi::create(['pais' => 'Angola', 'ddi' => '244']);
        TelefoneDdi::create(['pais' => 'Anguilla', 'ddi' => '1 264']);
        TelefoneDdi::create(['pais' => 'Antarctica', 'ddi' => '672']);
        TelefoneDdi::create(['pais' => 'Antígua e Barbuda', 'ddi' => '1 268']);
        TelefoneDdi::create(['pais' => 'Argentina', 'ddi' => '54']);
        TelefoneDdi::create(['pais' => 'Argélia', 'ddi' => '213']);
        TelefoneDdi::create(['pais' => 'Arménia', 'ddi' => '374']);
        TelefoneDdi::create(['pais' => 'Aruba', 'ddi' => '297']);
        TelefoneDdi::create(['pais' => 'Arábia Saudita', 'ddi' => '966']);
        TelefoneDdi::create(['pais' => 'Austrália', 'ddi' => '61']);
        TelefoneDdi::create(['pais' => 'Áustria', 'ddi' => '43']);
        TelefoneDdi::create(['pais' => 'Azerbaijão', 'ddi' => '994']);
        TelefoneDdi::create(['pais' => 'Bahamas', 'ddi' => '1 242']);
        TelefoneDdi::create(['pais' => 'Bahrein', 'ddi' => '973']);
        TelefoneDdi::create(['pais' => 'Bangladesh', 'ddi' => '880']);
        TelefoneDdi::create(['pais' => 'Barbados', 'ddi' => '1 246']);
        TelefoneDdi::create(['pais' => 'Bélgica', 'ddi' => '32']);
        TelefoneDdi::create(['pais' => 'Belize', 'ddi' => '501']);
        TelefoneDdi::create(['pais' => 'Benim', 'ddi' => '229']);
        TelefoneDdi::create(['pais' => 'Bermuda', 'ddi' => '1 441']);
        TelefoneDdi::create(['pais' => 'Butão', 'ddi' => '975']);
        TelefoneDdi::create(['pais' => 'Bielorrússia', 'ddi' => '375']);
        TelefoneDdi::create(['pais' => 'Bolívia', 'ddi' => '591']);
        TelefoneDdi::create(['pais' => 'Bósnia e Herzegovina', 'ddi' => '387']);
        TelefoneDdi::create(['pais' => 'Botswana', 'ddi' => '267']);
        TelefoneDdi::create(['pais' => 'Brasil', 'ddi' => '55']);
        TelefoneDdi::create(['pais' => 'British Indian Ocean Territory', 'ddi' => '']);
        TelefoneDdi::create(['pais' => 'Brunei', 'ddi' => '673']);
        TelefoneDdi::create(['pais' => 'Bulgária', 'ddi' => '359']);
        TelefoneDdi::create(['pais' => 'Burkina Faso', 'ddi' => '226']);
        TelefoneDdi::create(['pais' => 'Myanmar (Burma)', 'ddi' => '95']);
        TelefoneDdi::create(['pais' => 'Burundi', 'ddi' => '257']);
        TelefoneDdi::create(['pais' => 'Camarões', 'ddi' => '237']);
        TelefoneDdi::create(['pais' => 'Cabo Verde', 'ddi' => '238']);
        TelefoneDdi::create(['pais' => 'Camboja', 'ddi' => '855']);
        TelefoneDdi::create(['pais' => 'Canadá', 'ddi' => '1']);
        TelefoneDdi::create(['pais' => 'Catar', 'ddi' => '974']);
        TelefoneDdi::create(['pais' => 'Chad', 'ddi' => '235']);
        TelefoneDdi::create(['pais' => 'Chile', 'ddi' => '56']);
        TelefoneDdi::create(['pais' => 'China', 'ddi' => '86']);
        TelefoneDdi::create(['pais' => 'Chipre', 'ddi' => '357']);
        TelefoneDdi::create(['pais' => 'Christmas Island', 'ddi' => '61']);
        TelefoneDdi::create(['pais' => 'Cingapura', 'ddi' => '65']);
        TelefoneDdi::create(['pais' => 'Colômbia', 'ddi' => '57']);
        TelefoneDdi::create(['pais' => 'Comores', 'ddi' => '269']);
        TelefoneDdi::create(['pais' => 'Coreia do Norte', 'ddi' => '850']);
        TelefoneDdi::create(['pais' => 'Coreia do Sul', 'ddi' => '82']);
        TelefoneDdi::create(['pais' => 'Costa do Marfim', 'ddi' => '225']);
        TelefoneDdi::create(['pais' => 'Costa Rica', 'ddi' => '506']);
        TelefoneDdi::create(['pais' => 'Croácia', 'ddi' => '385']);
        TelefoneDdi::create(['pais' => 'Cuba', 'ddi' => '53']);
        TelefoneDdi::create(['pais' => 'Dinamarca', 'ddi' => '45']);
        TelefoneDdi::create(['pais' => 'Djibouti', 'ddi' => '253']);
        TelefoneDdi::create(['pais' => 'Dominica', 'ddi' => '1 767']);
        TelefoneDdi::create(['pais' => 'Egito', 'ddi' => '20']);
        TelefoneDdi::create(['pais' => 'El Salvador', 'ddi' => '503']);
        TelefoneDdi::create(['pais' => 'Emirados Árabes Unidos', 'ddi' => '971']);
        TelefoneDdi::create(['pais' => 'Equador', 'ddi' => '593']);
        TelefoneDdi::create(['pais' => 'Eritreia', 'ddi' => '291']);
        TelefoneDdi::create(['pais' => 'Estónia', 'ddi' => '372']);
        TelefoneDdi::create(['pais' => 'Espanha', 'ddi' => '34']);
        TelefoneDdi::create(['pais' => 'Etiópia', 'ddi' => '251']);
        TelefoneDdi::create(['pais' => 'Fiji', 'ddi' => '679']);
        TelefoneDdi::create(['pais' => 'Finlândia', 'ddi' => '358']);
        TelefoneDdi::create(['pais' => 'França', 'ddi' => '33']);
        TelefoneDdi::create(['pais' => 'Gabão', 'ddi' => '241']);
        TelefoneDdi::create(['pais' => 'Gâmbia', 'ddi' => '220']);
        TelefoneDdi::create(['pais' => 'Banda de Gaza (Palestina)', 'ddi' => '970']);
        TelefoneDdi::create(['pais' => 'Geórgia', 'ddi' => '995']);
        TelefoneDdi::create(['pais' => 'Gana', 'ddi' => '233']);
        TelefoneDdi::create(['pais' => 'Gibraltar', 'ddi' => '350']);
        TelefoneDdi::create(['pais' => 'Grécia', 'ddi' => '30']);
        TelefoneDdi::create(['pais' => 'Groelândia', 'ddi' => '299']);
        TelefoneDdi::create(['pais' => 'Granada', 'ddi' => '1 473']);
        TelefoneDdi::create(['pais' => 'Guam', 'ddi' => '1 671']);
        TelefoneDdi::create(['pais' => 'Guatemala', 'ddi' => '502']);
        TelefoneDdi::create(['pais' => 'Guiana', 'ddi' => '592']);
        TelefoneDdi::create(['pais' => 'Guiné', 'ddi' => '224']);
        TelefoneDdi::create(['pais' => 'Guiné Equatorial', 'ddi' => '240']);
        TelefoneDdi::create(['pais' => 'Guiné-Bissau', 'ddi' => '245']);
        TelefoneDdi::create(['pais' => 'Haiti', 'ddi' => '509']);
        TelefoneDdi::create(['pais' => 'Honduras', 'ddi' => '504']);
        TelefoneDdi::create(['pais' => 'Hong Kong', 'ddi' => '852']);
        TelefoneDdi::create(['pais' => 'Hungria', 'ddi' => '36']);
        TelefoneDdi::create(['pais' => 'Islândia', 'ddi' => '354']);
        TelefoneDdi::create(['pais' => 'Ilhas Cayman', 'ddi' => '1 345']);
        TelefoneDdi::create(['pais' => 'Ilhas Cocos (Keeling)', 'ddi' => '61']);
        TelefoneDdi::create(['pais' => 'Ilha de Man', 'ddi' => '44']);
        TelefoneDdi::create(['pais' => 'Ilhas Cook', 'ddi' => '682']);
        TelefoneDdi::create(['pais' => 'Ilhas Falkland (Malvinas)', 'ddi' => '500']);
        TelefoneDdi::create(['pais' => 'Ilhas Feroé', 'ddi' => '298']);
        TelefoneDdi::create(['pais' => 'Ilhas Mariana do Norte', 'ddi' => '1 670']);
        TelefoneDdi::create(['pais' => 'Ilhas Marshall', 'ddi' => '692']);
        TelefoneDdi::create(['pais' => 'Ilhas Norfolk', 'ddi' => '672']);
        TelefoneDdi::create(['pais' => 'Ilhas Pitcairn', 'ddi' => '870']);
        TelefoneDdi::create(['pais' => 'Ilhas Salomão', 'ddi' => '677']);
        TelefoneDdi::create(['pais' => 'Ilhas Turcas e Caicos', 'ddi' => '1 649']);
        TelefoneDdi::create(['pais' => 'Ilhas Virgens Americanas', 'ddi' => '1 340']);
        TelefoneDdi::create(['pais' => 'Ilhas Virgens Britânicas', 'ddi' => '1 284']);
        TelefoneDdi::create(['pais' => 'India', 'ddi' => '91']);
        TelefoneDdi::create(['pais' => 'Indonésia', 'ddi' => '62']);
        TelefoneDdi::create(['pais' => 'Inglaterra (Reino Unido)', 'ddi' => '44']);
        TelefoneDdi::create(['pais' => 'Irã', 'ddi' => '98']);
        TelefoneDdi::create(['pais' => 'Iraque', 'ddi' => '964']);
        TelefoneDdi::create(['pais' => 'Irlanda', 'ddi' => '353']);
        TelefoneDdi::create(['pais' => 'Israel', 'ddi' => '972']);
        TelefoneDdi::create(['pais' => 'Itália', 'ddi' => '39']);
        TelefoneDdi::create(['pais' => 'Jamaica', 'ddi' => '1 876']);
        TelefoneDdi::create(['pais' => 'Japão', 'ddi' => '81']);
        TelefoneDdi::create(['pais' => 'Jersey', 'ddi' => '']);
        TelefoneDdi::create(['pais' => 'Jordânia', 'ddi' => '962']);
        TelefoneDdi::create(['pais' => 'Cazaquistão', 'ddi' => '7']);
        TelefoneDdi::create(['pais' => 'Quénia (Kenya)', 'ddi' => '254']);
        TelefoneDdi::create(['pais' => 'Kiribati', 'ddi' => '686']);
        TelefoneDdi::create(['pais' => 'Kosovo', 'ddi' => '381']);
        TelefoneDdi::create(['pais' => 'Kuwait', 'ddi' => '965']);
        TelefoneDdi::create(['pais' => 'Quirguistão', 'ddi' => '996']);
        TelefoneDdi::create(['pais' => 'Laos', 'ddi' => '856']);
        TelefoneDdi::create(['pais' => 'Letônia', 'ddi' => '371']);
        TelefoneDdi::create(['pais' => 'Líbano', 'ddi' => '961']);
        TelefoneDdi::create(['pais' => 'Lesoto', 'ddi' => '266']);
        TelefoneDdi::create(['pais' => 'Libéria', 'ddi' => '231']);
        TelefoneDdi::create(['pais' => 'Líbia', 'ddi' => '218']);
        TelefoneDdi::create(['pais' => 'Liechtenstein', 'ddi' => '423']);
        TelefoneDdi::create(['pais' => 'Lituânia', 'ddi' => '370']);
        TelefoneDdi::create(['pais' => 'Luxemburgo', 'ddi' => '352']);
        TelefoneDdi::create(['pais' => 'Macau', 'ddi' => '853']);
        TelefoneDdi::create(['pais' => 'Macedónia', 'ddi' => '389']);
        TelefoneDdi::create(['pais' => 'Madagáscar', 'ddi' => '261']);
        TelefoneDdi::create(['pais' => 'Malawi', 'ddi' => '265']);
        TelefoneDdi::create(['pais' => 'Malásia', 'ddi' => '60']);
        TelefoneDdi::create(['pais' => 'Maldivas', 'ddi' => '960']);
        TelefoneDdi::create(['pais' => 'Mali', 'ddi' => '223']);
        TelefoneDdi::create(['pais' => 'Malta', 'ddi' => '356']);
        TelefoneDdi::create(['pais' => 'Mauritânia', 'ddi' => '222']);
        TelefoneDdi::create(['pais' => 'Maurícia', 'ddi' => '230']);
        TelefoneDdi::create(['pais' => 'Mayotte', 'ddi' => '262']);
        TelefoneDdi::create(['pais' => 'México', 'ddi' => '52']);
        TelefoneDdi::create(['pais' => 'Micronésia', 'ddi' => '691']);
        TelefoneDdi::create(['pais' => 'Moldávia', 'ddi' => '373']);
        TelefoneDdi::create(['pais' => 'Monaco', 'ddi' => '377']);
        TelefoneDdi::create(['pais' => 'Mongólia', 'ddi' => '976']);
        TelefoneDdi::create(['pais' => 'Montenegro', 'ddi' => '382']);
        TelefoneDdi::create(['pais' => 'Montserrat', 'ddi' => '1 664']);
        TelefoneDdi::create(['pais' => 'Marrocos', 'ddi' => '212']);
        TelefoneDdi::create(['pais' => 'Moçambique', 'ddi' => '258']);
        TelefoneDdi::create(['pais' => 'Namíbia', 'ddi' => '264']);
        TelefoneDdi::create(['pais' => 'Nauru', 'ddi' => '674']);
        TelefoneDdi::create(['pais' => 'Nepal', 'ddi' => '977']);
        TelefoneDdi::create(['pais' => 'Netherlands Antilles', 'ddi' => '599']);
        TelefoneDdi::create(['pais' => 'Nova Caledônia', 'ddi' => '687']);
        TelefoneDdi::create(['pais' => 'Nova Zelândia', 'ddi' => '64']);
        TelefoneDdi::create(['pais' => 'Nicaragua', 'ddi' => '505']);
        TelefoneDdi::create(['pais' => 'Níger', 'ddi' => '227']);
        TelefoneDdi::create(['pais' => 'Nigéria', 'ddi' => '234']);
        TelefoneDdi::create(['pais' => 'Niue', 'ddi' => '683']);
        TelefoneDdi::create(['pais' => 'Noruega', 'ddi' => '47']);
        TelefoneDdi::create(['pais' => 'Omã', 'ddi' => '968']);
        TelefoneDdi::create(['pais' => 'Países Baixos', 'ddi' => '31']);
        TelefoneDdi::create(['pais' => 'Paquistão', 'ddi' => '92']);
        TelefoneDdi::create(['pais' => 'Palau', 'ddi' => '680']);
        TelefoneDdi::create(['pais' => 'Panamá', 'ddi' => '507']);
        TelefoneDdi::create(['pais' => 'Papua-Nova Guiné', 'ddi' => '675']);
        TelefoneDdi::create(['pais' => 'Paraguai', 'ddi' => '595']);
        TelefoneDdi::create(['pais' => 'Peru', 'ddi' => '51']);
        TelefoneDdi::create(['pais' => 'Filipinas', 'ddi' => '63']);
        TelefoneDdi::create(['pais' => 'Polónia', 'ddi' => '48']);
        TelefoneDdi::create(['pais' => 'Polinésia Francesa', 'ddi' => '689']);
        TelefoneDdi::create(['pais' => 'Portugal', 'ddi' => '351']);
        TelefoneDdi::create(['pais' => 'Porto Rico', 'ddi' => '1']);
        TelefoneDdi::create(['pais' => 'República do Congo', 'ddi' => '242']);
        TelefoneDdi::create(['pais' => 'República Democrática do Congo', 'ddi' => '243']);
        TelefoneDdi::create(['pais' => 'República Centro-Africana', 'ddi' => '236']);
        TelefoneDdi::create(['pais' => 'República Checa', 'ddi' => '420']);
        TelefoneDdi::create(['pais' => 'República Dominicana', 'ddi' => '1 809']);
        TelefoneDdi::create(['pais' => 'Roménia', 'ddi' => '40']);
        TelefoneDdi::create(['pais' => 'Ruanda', 'ddi' => '250']);
        TelefoneDdi::create(['pais' => 'Rússia', 'ddi' => '7']);
        TelefoneDdi::create(['pais' => 'Saint Barthelemy', 'ddi' => '590']);
        TelefoneDdi::create(['pais' => 'Samoa', 'ddi' => '685']);
        TelefoneDdi::create(['pais' => 'Samoa Americana', 'ddi' => '1 684']);
        TelefoneDdi::create(['pais' => 'San Marino', 'ddi' => '378']);
        TelefoneDdi::create(['pais' => 'Sao Tome e Principe', 'ddi' => '239']);
        TelefoneDdi::create(['pais' => 'Senegal', 'ddi' => '221']);
        TelefoneDdi::create(['pais' => 'Serbia', 'ddi' => '381']);
        TelefoneDdi::create(['pais' => 'Serra Leoa', 'ddi' => '232']);
        TelefoneDdi::create(['pais' => 'Seychelles', 'ddi' => '248']);
        TelefoneDdi::create(['pais' => 'Slovakia', 'ddi' => '421']);
        TelefoneDdi::create(['pais' => 'Slovenia', 'ddi' => '386']);
        TelefoneDdi::create(['pais' => 'Somalia', 'ddi' => '252']);
        TelefoneDdi::create(['pais' => 'Sri Lanka', 'ddi' => '94']);
        TelefoneDdi::create(['pais' => 'Saint Helena', 'ddi' => '290']);
        TelefoneDdi::create(['pais' => 'Saint Kitts and Nevis', 'ddi' => '1 869']);
        TelefoneDdi::create(['pais' => 'Saint Lucia', 'ddi' => '1 758']);
        TelefoneDdi::create(['pais' => 'Saint Martin', 'ddi' => '1 599']);
        TelefoneDdi::create(['pais' => 'Saint Pierre and Miquelon', 'ddi' => '508']);
        TelefoneDdi::create(['pais' => 'Saint Vincent and the Grenadines', 'ddi' => '1 784']);
        TelefoneDdi::create(['pais' => 'Sudão', 'ddi' => '249']);
        TelefoneDdi::create(['pais' => 'Suriname', 'ddi' => '597']);
        TelefoneDdi::create(['pais' => 'Svalbard', 'ddi' => '']);
        TelefoneDdi::create(['pais' => 'Suazilândia', 'ddi' => '268']);
        TelefoneDdi::create(['pais' => 'Suécia', 'ddi' => '46']);
        TelefoneDdi::create(['pais' => 'Suiça', 'ddi' => '41']);
        TelefoneDdi::create(['pais' => 'Syria', 'ddi' => '963']);
        TelefoneDdi::create(['pais' => 'Taiwan', 'ddi' => '886']);
        TelefoneDdi::create(['pais' => 'Tajiquistão', 'ddi' => '992']);
        TelefoneDdi::create(['pais' => 'Tanzânia', 'ddi' => '255']);
        TelefoneDdi::create(['pais' => 'Timor-Leste', 'ddi' => '670']);
        TelefoneDdi::create(['pais' => 'Tailândia', 'ddi' => '66']);
        TelefoneDdi::create(['pais' => 'Togo', 'ddi' => '228']);
        TelefoneDdi::create(['pais' => 'Tokelau', 'ddi' => '690']);
        TelefoneDdi::create(['pais' => 'Tonga', 'ddi' => '676']);
        TelefoneDdi::create(['pais' => 'Trinidad e Tobago', 'ddi' => '1 868']);
        TelefoneDdi::create(['pais' => 'Tunísia', 'ddi' => '216']);
        TelefoneDdi::create(['pais' => 'Turquemenistão', 'ddi' => '993']);
        TelefoneDdi::create(['pais' => 'Turquia', 'ddi' => '90']);
        TelefoneDdi::create(['pais' => 'Tuvalu', 'ddi' => '688']);
        TelefoneDdi::create(['pais' => 'Uganda', 'ddi' => '256']);
        TelefoneDdi::create(['pais' => 'Ucrânia', 'ddi' => '380']);
        TelefoneDdi::create(['pais' => 'Uruguai', 'ddi' => '598']);
        TelefoneDdi::create(['pais' => 'Estados Unidos (EUA)', 'ddi' => '1']);
        TelefoneDdi::create(['pais' => 'Uzbequistão', 'ddi' => '998']);
        TelefoneDdi::create(['pais' => 'Vanuatu', 'ddi' => '678']);
        TelefoneDdi::create(['pais' => 'Vaticano', 'ddi' => '39']);
        TelefoneDdi::create(['pais' => 'Venezuela', 'ddi' => '58']);
        TelefoneDdi::create(['pais' => 'Vietnã (Vietname)', 'ddi' => '84']);
        TelefoneDdi::create(['pais' => 'Wallis e Futuna', 'ddi' => '681']);
        TelefoneDdi::create(['pais' => 'West Bank', 'ddi' => '970']);
        TelefoneDdi::create(['pais' => 'Western Sahara', 'ddi' => '']);
        TelefoneDdi::create(['pais' => 'Iémen (Iémen, Yemen)', 'ddi' => '967']);
        TelefoneDdi::create(['pais' => 'Zimbabwe(Zimbabué)', 'ddi' => '263']);
        TelefoneDdi::create(['pais' => 'Zâmbia', 'ddi' => '260']);
    }
}
