<?php

namespace Database\Seeders;

use App\Models\VisitaTecnicaPergunta;
use App\Models\VisitaTecnicaStatus;
use App\Models\VisitaTecnicaTipo;
use Illuminate\Database\Seeder;

class ZZZ_20250529_Seeder extends Seeder
{
    /*
     * Sempre que tiver alterações de Seeder depois do dia 15 de março de 2025 fazer um arquivo Z_99999999_Seeder.php
     * Desenvolvimento : colocar no arquivo DatabaseSeeder.php
     * Produção : rodar uma única vez
     */

    public function run()
    {
        //Visita Técnica Tipos
        VisitaTecnicaTipo::create(['id' => 1, 'name' => 'EXAUSTÃO']);
        VisitaTecnicaTipo::create(['id' => 2, 'name' => 'INCÊNDIO']);

        //Visita Técnica Status
        VisitaTecnicaStatus::create(['id' => 1, 'name' => 'ABERTA']);
        VisitaTecnicaStatus::create(['id' => 2, 'name' => 'EM ANDAMENTO']);
        VisitaTecnicaStatus::create(['id' => 3, 'name' => 'CONCLUÍDA']);
        VisitaTecnicaStatus::create(['id' => 4, 'name' => 'FINALIZADA']);
        VisitaTecnicaStatus::create(['id' => 5, 'name' => 'CANCELADA']);

        //Visita Técnica Perguntas
        VisitaTecnicaPergunta::create(['id' => 1, 'visita_tecnica_tipo_id' => 1, 'ordem' => 10, 'titulo' => 'DA DOCUMENTAÇÃO JUNTO AO CORPO DE BOMBEIROS MILITAR DO ESTADO DO RIO DE JANEIRO', 'subtitulo' => '', 'pergunta' => 'PROJETO DE SEGURANÇA CONTRA INCÊNDIO E PÂNICO APROVADO', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 2, 'visita_tecnica_tipo_id' => 1, 'ordem' => 20, 'titulo' => 'DA DOCUMENTAÇÃO JUNTO AO CORPO DE BOMBEIROS MILITAR DO ESTADO DO RIO DE JANEIRO', 'subtitulo' => '', 'pergunta' => 'LAUDO DE EXIGÊNCIAS', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 3, 'visita_tecnica_tipo_id' => 1, 'ordem' => 30, 'titulo' => 'DA DOCUMENTAÇÃO JUNTO AO CORPO DE BOMBEIROS MILITAR DO ESTADO DO RIO DE JANEIRO', 'subtitulo' => '', 'pergunta' => 'CERTIFICADO DE APROVAÇÃO', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 4, 'visita_tecnica_tipo_id' => 1, 'ordem' => 40, 'titulo' => 'DA DOCUMENTAÇÃO JUNTO A GERÊNCIA DE ENGENHARIA DA PREFEITURA MUNICIPAL DO RIO DE JANEIRO', 'subtitulo' => '', 'pergunta' => 'MEMÓRIA DESCRITIVA', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 5, 'visita_tecnica_tipo_id' => 1, 'ordem' => 50, 'titulo' => 'DA DOCUMENTAÇÃO JUNTO A GERÊNCIA DE ENGENHARIA DA PREFEITURA MUNICIPAL DO RIO DE JANEIRO', 'subtitulo' => '', 'pergunta' => 'CERTIFICADO DE FUNCIONAMENTO', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 6, 'visita_tecnica_tipo_id' => 1, 'ordem' => 60, 'titulo' => 'DOS REQUISITOS GERAIS', 'subtitulo' => '', 'pergunta' => 'SISTEMA DE EXAUSTÃO DE COZINHA EXCLUSIVO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 7, 'visita_tecnica_tipo_id' => 1, 'ordem' => 70, 'titulo' => 'DOS REQUISITOS GERAIS', 'subtitulo' => '', 'pergunta' => 'COIFAS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 8, 'visita_tecnica_tipo_id' => 1, 'ordem' => 80, 'titulo' => 'DOS REQUISITOS GERAIS', 'subtitulo' => '', 'pergunta' => 'REDE DE DUTOS E ACESSÓRIOS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 9, 'visita_tecnica_tipo_id' => 1, 'ordem' => 90, 'titulo' => 'DOS REQUISITOS GERAIS', 'subtitulo' => '', 'pergunta' => 'VENTILADORES ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 10, 'visita_tecnica_tipo_id' => 1, 'ordem' => 100, 'titulo' => 'DOS REQUISITOS GERAIS', 'subtitulo' => '', 'pergunta' => 'DISPOSITIVOS E EQUIPAMENTOS PARA TRATAMENTO DE  AR EXCLUSIVO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 11, 'visita_tecnica_tipo_id' => 1, 'ordem' => 110, 'titulo' => 'DOS REQUISITOS GERAIS', 'subtitulo' => '', 'pergunta' => 'DISPOSITIVOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 12, 'visita_tecnica_tipo_id' => 1, 'ordem' => 120, 'titulo' => 'DOS REQUISITOS GERAIS', 'subtitulo' => '', 'pergunta' => 'COMPENSAÇÃO DO AR EXAURIDO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 13, 'visita_tecnica_tipo_id' => 1, 'ordem' => 130, 'titulo' => 'DAS COIFAS', 'subtitulo' => '', 'pergunta' => 'QUANTAS COIFAS ?', 'respostas' => 'numero']);
        VisitaTecnicaPergunta::create(['id' => 14, 'visita_tecnica_tipo_id' => 1, 'ordem' => 140, 'titulo' => 'DAS COIFAS', 'subtitulo' => '', 'pergunta' => 'COIFAS INSTALADAS SOBRE FONTES EMISSORAS DE CONTAMINANTES ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 15, 'visita_tecnica_tipo_id' => 1, 'ordem' => 150, 'titulo' => 'DAS COIFAS', 'subtitulo' => '', 'pergunta' => 'O MATERIAL CONSTRUTIVO METÁLICO É NÃO COMBSUTÍVEL ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 16, 'visita_tecnica_tipo_id' => 1, 'ordem' => 160, 'titulo' => 'DAS COIFAS', 'subtitulo' => '', 'pergunta' => 'A(S) COIFA(S) POSSUI(EM) SUPERFÍCIES INTERNAS LISAS E FÁCIL DE LIMPAR ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 17, 'visita_tecnica_tipo_id' => 1, 'ordem' => 170, 'titulo' => 'DAS COIFAS', 'subtitulo' => '', 'pergunta' => 'AUSÊNCIA DE REENTRÂNCIAS OU PONTOS DE ACÚMULO DE GORDURA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 18, 'visita_tecnica_tipo_id' => 1, 'ordem' => 180, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'ESTILO DAS COIFAS', 'pergunta' => 'TIPO DA COIFA (PAREDE / CENTRAL / ILHA) ADEQUADO AO LAYOUT ?', 'respostas' => '']);
        VisitaTecnicaPergunta::create(['id' => 19, 'visita_tecnica_tipo_id' => 1, 'ordem' => 190, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'ESTILO DAS COIFAS', 'pergunta' => 'PROPORCIONALIDADE ENTRE DIMENSÕES DA COIFA E ÁREA DE COCÇÃO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 20, 'visita_tecnica_tipo_id' => 1, 'ordem' => 200, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'ESTILO DAS COIFAS', 'pergunta' => 'INCLINAÇÃO ADEQUADA PARA FACILITAR O ESCOAMENTO DE GORDURA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 21, 'visita_tecnica_tipo_id' => 1, 'ordem' => 210, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'ASPECTOS CONSTRUTIVOS', 'pergunta' => 'JUNTAS E SOLDAS CONTÍNUAS E ESTANQUES ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 22, 'visita_tecnica_tipo_id' => 1, 'ordem' => 220, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'ASPECTOS CONSTRUTIVOS', 'pergunta' => 'PRESENÇA DE CALHAS COLETORAS DE GORDURA COM DRENO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 23, 'visita_tecnica_tipo_id' => 1, 'ordem' => 230, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'ASPECTOS CONSTRUTIVOS', 'pergunta' => 'PROPORCIONALIDADE ENTRE DIMENSÕES DA COIFA E ÁREA DE COCÇÃO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 24, 'visita_tecnica_tipo_id' => 1, 'ordem' => 240, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'ASPECTOS CONSTRUTIVOS', 'pergunta' => 'PRESENÇA DE DEFLETORES OU FILTROS METÁLICOS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 25, 'visita_tecnica_tipo_id' => 1, 'ordem' => 250, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'ASPECTOS CONSTRUTIVOS', 'pergunta' => 'RESISTÊNCIA MECÂNICA E FIXAÇÃO DA COIFA SEGURA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 26, 'visita_tecnica_tipo_id' => 1, 'ordem' => 260, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'REDE DE DUTOS E ACESSÓRIOS', 'pergunta' => 'DUTOS METÁLICOS E NÃO COMBUSTÍVEIS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 27, 'visita_tecnica_tipo_id' => 1, 'ordem' => 270, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'REDE DE DUTOS E ACESSÓRIOS', 'pergunta' => 'VEDAÇÃO CORRETA NAS CONEXÕES E EMENDAS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 28, 'visita_tecnica_tipo_id' => 1, 'ordem' => 280, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'REDE DE DUTOS E ACESSÓRIOS', 'pergunta' => 'AUSÊNCIA DE VAZAMENTO DE AR OU GORDURA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 29, 'visita_tecnica_tipo_id' => 1, 'ordem' => 290, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'REDE DE DUTOS E ACESSÓRIOS', 'pergunta' => 'INCLINAÇÃO FAVORÁVEL AO ESCOAMENTO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 30, 'visita_tecnica_tipo_id' => 1, 'ordem' => 300, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'REDE DE DUTOS E ACESSÓRIOS', 'pergunta' => 'ISOLAMENTO TÉRMICO PRESENTE (QUANDO EXIGIDO) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 31, 'visita_tecnica_tipo_id' => 1, 'ordem' => 310, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'PORTAS DE INSPEÇÃO', 'pergunta' => 'PORTAS DE INSPEÇÃO INSTALADAS A CADA 3 METROS (MÍNIMO) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 32, 'visita_tecnica_tipo_id' => 1, 'ordem' => 320, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'PORTAS DE INSPEÇÃO', 'pergunta' => 'ACESSO DESOBSTRUÍDO E SEGURO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 33, 'visita_tecnica_tipo_id' => 1, 'ordem' => 330, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'PORTAS DE INSPEÇÃO', 'pergunta' => 'DIMENSÕES ADEQUADAS PARA INSPEÇÃO E LIMPEZA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 37, 'visita_tecnica_tipo_id' => 1, 'ordem' => 370, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'TERMINAL DE DESCARGA', 'pergunta' => 'POSICIONADO CONFORME NORMA (ACIMA DE TELHADOS, AFASTAMENTO DE JANELAS) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 38, 'visita_tecnica_tipo_id' => 1, 'ordem' => 380, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'TERMINAL DE DESCARGA', 'pergunta' => 'FLUXO LIVRE DE OBSTRUÇÕES ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 39, 'visita_tecnica_tipo_id' => 1, 'ordem' => 390, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'TERMINAL DE DESCARGA', 'pergunta' => 'TERMINAL POSSUI PROTEÇÃO CONTRA INTEMPÉRIES OU ANIMAIS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 40, 'visita_tecnica_tipo_id' => 1, 'ordem' => 400, 'titulo' => 'DAS COIFAS', 'subtitulo' => 'TERMINAL DE DESCARGA', 'pergunta' => 'CONFORMIDADE COM NÍVEL DE RUÍDO PERMITIDO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 41, 'visita_tecnica_tipo_id' => 1, 'ordem' => 410, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'VENTILADOR INSTALADO FORA DO FLUXO DIRETO DE VAPORES E GORDURA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 42, 'visita_tecnica_tipo_id' => 1, 'ordem' => 420, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'VENTILADOR INSTALADO FORA DO AMBIENTE DA COZINHA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 43, 'visita_tecnica_tipo_id' => 1, 'ordem' => 430, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'TIPO DO VENTILADOR É COMPATÍVEL COM O SISTEMA (CENTRÍFUGO OU AXIAL CONFORME PROJETO) ?', 'respostas' => 'centrífugo#axial#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 44, 'visita_tecnica_tipo_id' => 1, 'ordem' => 440, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'DISPOSITIVO DE PROTEÇÃO CONTRA RETORNO DE AR PRESENTE (EX: DAMPER ANTIRRETORNO) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 45, 'visita_tecnica_tipo_id' => 1, 'ordem' => 450, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'FACILIDADE DE ACESSO PARA MANUTENÇÃO E LIMPEZA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 46, 'visita_tecnica_tipo_id' => 1, 'ordem' => 460, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'COMPONENTES MECÂNICOS PROTEGIDOS CONTRA CONTATO ACIDENTAL (CARENAGENS OU GRADES) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 47, 'visita_tecnica_tipo_id' => 1, 'ordem' => 470, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'VENTILADOR FIXADO ADEQUADAMENTE À ESTRUTURA DE APOIO (SEM FOLGAS, SUPORTES ESTÁVEIS) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 48, 'visita_tecnica_tipo_id' => 1, 'ordem' => 480, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'EXISTÊNCIA DE PONTO DE INSPEÇÃO OU VISUALIZAÇÃO DO ESTADO DO EQUIPAMENTO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 49, 'visita_tecnica_tipo_id' => 1, 'ordem' => 490, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'CABOS ELÉTRICOS PROTEGIDOS E CONECTADOS CONFORME NORMAS DE INSTALAÇÕES ELÉTRICAS (EX: NBR 5410) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 50, 'visita_tecnica_tipo_id' => 1, 'ordem' => 500, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'SELO DE IDENTIFICAÇÃO DO FABRICANTE COM DADOS TÉCNICOS VISÍVEL ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 51, 'visita_tecnica_tipo_id' => 1, 'ordem' => 510, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'PROTEÇÃO TÉRMICA DO MOTOR INSTALADA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 52, 'visita_tecnica_tipo_id' => 1, 'ordem' => 520, 'titulo' => 'TERMINAL DE DESCARGA', 'subtitulo' => '', 'pergunta' => 'SELO DE IDENTIFICAÇÃO DO FABRICANTE COM DADOS TÉCNICOS VISÍVEL ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 53, 'visita_tecnica_tipo_id' => 1, 'ordem' => 530, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => '', 'pergunta' => 'PRESENÇA DE FILTROS MECÂNICOS (EX: FILTROS METÁLICOS, FILTROS INERCIAIS) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 54, 'visita_tecnica_tipo_id' => 1, 'ordem' => 540, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => '', 'pergunta' => 'PRESENÇA DE FILTROS PARA ODORES (EX: CARVÃO ATIVADO, BIOFILTROS OU EQUIVALENTES) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 55, 'visita_tecnica_tipo_id' => 1, 'ordem' => 550, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => '', 'pergunta' => 'FÁCIL ACESSO PARA INSPEÇÃO, RETIRADA E LIMPEZA DOS FILTROS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 56, 'visita_tecnica_tipo_id' => 1, 'ordem' => 560, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => '', 'pergunta' => 'SUBSTITUIÇÃO E LIMPEZA DOS FILTROS COM FREQUÊNCIA DEFINIDA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 57, 'visita_tecnica_tipo_id' => 1, 'ordem' => 570, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => '', 'pergunta' => 'REGISTRO OU CONTROLE DE MANUTENÇÃO DOS FILTROS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 58, 'visita_tecnica_tipo_id' => 1, 'ordem' => 580, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'DISPOSITIVOS EXTRATORES (VENTILADORES + COMPONENTES ASSOCIADOS)', 'pergunta' => 'BOA VEDAÇÃO ENTRE COIFA E DUTO DE EXAUSTÃO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 59, 'visita_tecnica_tipo_id' => 1, 'ordem' => 590, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'DISPOSITIVOS EXTRATORES (VENTILADORES + COMPONENTES ASSOCIADOS)', 'pergunta' => 'NÍVEL DE RUÍDO DO EXTRATOR DENTRO DOS LIMITES ACEITÁVEIS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 60, 'visita_tecnica_tipo_id' => 1, 'ordem' => 600, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'DISPOSITIVOS EXTRATORES (VENTILADORES + COMPONENTES ASSOCIADOS)', 'pergunta' => 'PRESENÇA DE ISOLAMENTO ANTIVIBRATÓRIO (QUANDO NECESSÁRIO) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 61, 'visita_tecnica_tipo_id' => 1, 'ordem' => 610, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'DISPOSITIVOS EXTRATORES (VENTILADORES + COMPONENTES ASSOCIADOS)', 'pergunta' => 'ACESSO SEGURO PARA INSPEÇÃO E MANUTENÇÃO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 62, 'visita_tecnica_tipo_id' => 1, 'ordem' => 620, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'LAVAORES DE GORDURA E DE GASES', 'pergunta' => 'LAVADOR COMPATÍVEL COM O TIPO DE CONTAMINANTES GERADOS (EX: GORDURA, ODOR) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 63, 'visita_tecnica_tipo_id' => 1, 'ordem' => 630, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'LAVAORES DE GORDURA E DE GASES', 'pergunta' => 'LAVADOR POSSUI SISTEMA DE CIRCULAÇÃO E REPOSIÇÃO DE ÁGUA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 64, 'visita_tecnica_tipo_id' => 1, 'ordem' => 640, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'LAVAORES DE GORDURA E DE GASES', 'pergunta' => 'EFICIÊNCIA DE RETENÇÃO MÍNIMA DE 70% CONFORME NBR 14518 ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 65, 'visita_tecnica_tipo_id' => 1, 'ordem' => 650, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'LAVAORES DE GORDURA E DE GASES', 'pergunta' => 'ACESSO FÁCIL PARA LIMPEZA DOS BICOS, BANDEJAS E TANQUES ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 66, 'visita_tecnica_tipo_id' => 1, 'ordem' => 660, 'titulo' => 'FILTROS E DESPOLUIDORES ATMOSFÉRICOS', 'subtitulo' => 'LAVAORES DE GORDURA E DE GASES', 'pergunta' => 'FREQUÊNCIA DE MANUTENÇÃO PROGRAMADA E REGISTRADA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 67, 'visita_tecnica_tipo_id' => 1, 'ordem' => 670, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'TODOS OS ELEMENTOS DO SISTEMA (COIFAS, DUTOS, VENTILADORES) SÃO CONSTRUÍDOS COM MATERIAIS NÃO COMBUSTÍVEIS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 68, 'visita_tecnica_tipo_id' => 1, 'ordem' => 680, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'INSTALAÇÃO POSSUI ISOLAMENTO TÉRMICO ADEQUADO ONDE HÁ PROXIMIDADE COM ESTRUTURAS COMBUSTÍVEIS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 69, 'visita_tecnica_tipo_id' => 1, 'ordem' => 690, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'RESPEITO AOS DIMENSIONAMENTOS MÍNIMOS DE SEGURANÇA ENTRE DUTOS E MATERIAIS INFLAMÁVEIS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 70, 'visita_tecnica_tipo_id' => 1, 'ordem' => 700, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'SISTEMAS DE EXAUSTÃO POSSUI DAMPER CORTA FOGO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 71, 'visita_tecnica_tipo_id' => 1, 'ordem' => 710, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'PRESENÇA DE REDE DE CHUVEIROS AUTOMÁTICOS DO TIPO SPRINKLERS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 72, 'visita_tecnica_tipo_id' => 1, 'ordem' => 720, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'SISTEMA DE DETECÇÃO DE FUMAÇA E ALARME DE INCÊNDIO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 73, 'visita_tecnica_tipo_id' => 1, 'ordem' => 730, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'SISTEMA DE CO2 ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 74, 'visita_tecnica_tipo_id' => 1, 'ordem' => 740, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'SAPONIFICANTE ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 75, 'visita_tecnica_tipo_id' => 1, 'ordem' => 750, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'SISTEMA DE EXAUSTÃO POSSUI DISPOSITIVO DE DESLIGAMENTO AUTOMÁTICO DO GÁS EM CASO DE INCÊNDIO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 76, 'visita_tecnica_tipo_id' => 1, 'ordem' => 760, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'ACESSO AOS EQUIPAMENTOS DE SEGURANÇA CONTRA INCÊNDIO FACILITADO E SINALIZADO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 77, 'visita_tecnica_tipo_id' => 1, 'ordem' => 770, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'INSPEÇÃO E LIMPEZA PERIÓDICA DOS COMPONENTES DO SISTEMA DE EXAUSTÃO (PRINCIPALMENTE FILTROS E DUTOS) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 78, 'visita_tecnica_tipo_id' => 1, 'ordem' => 780, 'titulo' => 'ELEMENTOS DE PREVENÇÃO E PROTEÇÃO CONTRA INCÊNDIO', 'subtitulo' => '', 'pergunta' => 'EXISTÊNCIA DE REGISTROS DE PREVENTIVA E CORRETIVA DOS SISTEMAS PREVENTIVOS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 79, 'visita_tecnica_tipo_id' => 1, 'ordem' => 790, 'titulo' => 'PROCEDIMENTOS OPERACIONAIS', 'subtitulo' => '', 'pergunta' => 'EXISTE MANUAL DE OPERAÇÃO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 80, 'visita_tecnica_tipo_id' => 1, 'ordem' => 800, 'titulo' => 'PROCEDIMENTOS OPERACIONAIS', 'subtitulo' => '', 'pergunta' => 'MANUAL DE OPERAÇÃO ESTA DISPONÍVEL NO LOCAL E DE FÁCIL ACESSO AOS RESPONSÁVEIS PELA OPERAÇÃO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 81, 'visita_tecnica_tipo_id' => 1, 'ordem' => 810, 'titulo' => 'PROCEDIMENTOS OPERACIONAIS', 'subtitulo' => '', 'pergunta' => 'O SISTEMA É OPERADO POR PESSOAL TREINADO PARA USO CORRETO DOS EQUIPAMENTOS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 82, 'visita_tecnica_tipo_id' => 1, 'ordem' => 820, 'titulo' => 'PROCEDIMENTOS OPERACIONAIS', 'subtitulo' => '', 'pergunta' => 'MANUTEÇÃO E LIMPEZA REALIZADA POR EMPRESA OU PROFISSIONAIS QUALIFICADOS COM EMISSÃO DE ART ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 83, 'visita_tecnica_tipo_id' => 1, 'ordem' => 830, 'titulo' => 'PROCEDIMENTOS OPERACIONAIS', 'subtitulo' => '', 'pergunta' => 'EXISTE CRONOGRAMA DE MANUTENÇÃO E LIMPEZA DEFINIDO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 84, 'visita_tecnica_tipo_id' => 1, 'ordem' => 840, 'titulo' => 'PROCEDIMENTOS OPERACIONAIS', 'subtitulo' => '', 'pergunta' => 'HÁ CONTROLE DE FREQUÊNCIA DE SUBSTITUIÇÃO DE FILTROS (INERCIAIS, CARVÃO METÁLICOS, ETC...) ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 85, 'visita_tecnica_tipo_id' => 1, 'ordem' => 850, 'titulo' => 'PROCEDIMENTOS OPERACIONAIS', 'subtitulo' => '', 'pergunta' => 'O SISTEMA DE EXAUSTÃO É LIGADO ANTES DO INÍCIO DAS ATIVIDADES DE COCÇÃO E DESLIGADO APÓS O TÉRMINO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 86, 'visita_tecnica_tipo_id' => 1, 'ordem' => 860, 'titulo' => 'PROCEDIMENTOS OPERACIONAIS', 'subtitulo' => '', 'pergunta' => 'HÁ RELATÓRIOS PERIÓDICOS DE VISTORIA TÉCNICA DOCUMENTANDO AS CONSIÇÕES DO SISTEMA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 87, 'visita_tecnica_tipo_id' => 1, 'ordem' => 870, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'AS INSTALAÇÕES COM FORNOS, CHURRASQUEIRAS OU FOGÕES A LENHA OU CARVÃO POSSUEM SISTEMA DE EXAUSTÃO DEDICADO INDEPENDENTE ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 88, 'visita_tecnica_tipo_id' => 1, 'ordem' => 880, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'PRESENÇA DE DEFLETORES OU FILTROS ADEQUADOS PARA ALTA CARGA DE PARTÍCULAS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 89, 'visita_tecnica_tipo_id' => 1, 'ordem' => 890, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'DUTOS CONSTRUÍDOS COM MATERIAL METÁLICO, CONTÍNUO E COM ESPESSURA COMPATÍVEL COM ALTA TEMPERATURA ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 90, 'visita_tecnica_tipo_id' => 1, 'ordem' => 900, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'DUTOS COM ISOLAMENTO TÉRMICO ADEQUADO, QUANDO EM CONTATO COM ELEMENTOS COMBUSTÍVEIS ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 91, 'visita_tecnica_tipo_id' => 1, 'ordem' => 910, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'INCLINAÇÃO FIXAÇÃO E TRAJETO DOS DUTOS FAVORECEM O ESCOAMENTO E EVITAM PONTOS DE ACÚMULO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 92, 'visita_tecnica_tipo_id' => 1, 'ordem' => 920, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'SISTEMA DE DETECÇÃO DE FUMAÇA E ALARME DE INCÊNDIO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 93, 'visita_tecnica_tipo_id' => 1, 'ordem' => 930, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'SISTEMA DE CO2 ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 94, 'visita_tecnica_tipo_id' => 1, 'ordem' => 940, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'SAPONIFICANTE ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 95, 'visita_tecnica_tipo_id' => 1, 'ordem' => 950, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'EXISTEM PONTOS DE INSPEÇÃO ADICIONAIS EM PONTOS CRÍTICOS PARA LIMPEZA E MONITORAMENTO ?', 'respostas' => 'sim#não#não avaliado']);
        VisitaTecnicaPergunta::create(['id' => 96, 'visita_tecnica_tipo_id' => 1, 'ordem' => 960, 'titulo' => 'REQUISITOS ADICIONAIS PARA COMBUSTÍVEIS SÓLIDOS', 'subtitulo' => '', 'pergunta' => 'PROCEDIMENTO DE LIMPEZA E REMOÇÃO DE FULIGEM OUCREOSOTO DOCUMENTADO E COM PERIODICIDADE DEFINDA ?', 'respostas' => 'sim#não#não avaliado']);
    }
}
